### ISSUE TITLE
[Backend] Add new homework task (Homework name)

### ISSUE THREAD

**Issue by Ewa032** [WomenPlusPlus/deploy-impact-22-wikimini-b#107]
**Acceptance Criteria:**
- #104 
- #105 
- https://www.figma.com/file/GyaAuxiHncjTtKnC7duPUv/Wikimini?node-id=516%3A1814

Implement addNewHwForClass, getHwTask and updateHwTask endpoints functionality, so the teacher is able to add a new homework task for the students of a class and edit it for a single student
Notify the student (-> how to implement?)

**Comment by lucianak** [comment]
UpdateHwTask is not implemented as it's not in the current UI to edit a homework task
