### ISSUE TITLE
Choose front end stack & decide on the implementation options

### ISSUE THREAD

**Issue by Ewa032** [WomenPlusPlus/deploy-impact-22-wikimini-b#2]
1. Angular, React, Plain old HTML/CSS..
2. Implementation options:
- [ ] Mediawiki as CMS and Frontend 
- [x] Mediawiki as CMS with a web framework using the Mediawiki API

**Comment by lucianak** [comment]
see #5

**Comment by quaverous2** [comment]
As of Front End Meeting 13/10/2022:

Front End Framework:
Angular

Basic Component Library:
t.b.d. between Angular Material and PrimeNG

Styling:
Plain CSS with possibility to expand into post/preprocessors as need be

**Comment by Ewa032** [comment]
It was decided to proceed with Angular.
