### ISSUE TITLE
Define how to self-host backend structure on local machines

### ISSUE THREAD

**Issue by Ewa032** [WomenPlusPlus/deploy-impact-22-wikimini-b#3]
- Tomcat, nginx, etc

**Comment by quaverous2** [comment]
Exploring laragon-portable as DB / MediaWiki localhost solution

**Comment by lucianak** [comment]
Laragon seems to be only available for windows though, personally I use linux and I'm not sure if maybe other people in the team use macs

**Comment by lucianak** [comment]
Exploring docker (https://hub.docker.com/_/mediawiki) as localhost solution

**Comment by quaverous2** [comment]
> Laragon seems to be only available for windows though, personally I use linux and I'm not sure if maybe other people in the team use macs

You're right, better not to use that then.

> Exploring docker (https://hub.docker.com/_/mediawiki) as localhost solution

This is much better than a quick band-aid solution and we could use two containers, one for backend server and one for DB, to make everything replicable on an eventual remote hosting space

**Comment by lucianak** [comment]
Pulling and running mediawiki and MariaDb is working well for me so far and easy to set up, I still need to figure out how the linking works because the provided stack script didn't work for me. I'll try to figure this out tomorrow during the day before the back-end meeting.
Am 10. Okt. 2022, 23:44 +0200 schrieb Antonio Ancona ***@***.***>:

**Comment by lucianak** [comment]
Other possibilities: https://www.mediawiki.org/wiki/Software_bundles#MediaWiki_software_appliances

**Comment by lucianak** [comment]
After discussion in the back-end meeting we decided to use docker (https://hub.docker.com/_/mediawiki) with three linked containers: one for mediawiki using the official image, one for MariaDB using the official image, and one for our own backend.
