### ISSUE TITLE
Define a basic server structure with WikiMedia software accessible by developers

### ISSUE THREAD

**Issue by Ewa032** [WomenPlusPlus/deploy-impact-22-wikimini-b#4]

**Comment by quaverous2** [comment]
As per what asked by the team to PO:

Do we have a server to host our code or is everything local until presentation/delivery? - I would start locally first, install Mediawiki and play around. You can also use a `https://www.mediawiki.org/wiki/Hosting_services`

https://miraheze.org/ seems like a good online, free solution to host our wiki

**Comment by lucianak** [comment]
After discussion in the back-end meeting, we decided to host locally in a test environment for now and decide on the hosting service later when we have a better idea of the requirements.

**Comment by Ewa032** [comment]
@lucianak I forgot to ask about that one. To we want to complete it in the 3rd sprint?

**Comment by lucianak** [comment]
@Ewa032 I think it's not the most urgent for now and we should leave it in the backlog for this week and revisit it next sprint
