### ISSUE TITLE
Define the deployment system (CI/CD pipeline)

### ISSUE THREAD

**Issue by Ewa032** [WomenPlusPlus/deploy-impact-22-wikimini-b#6]
Possibilities: use the inbuilt GitHub CI/CD tools, use other (free) offers such as Jenkins, TeamCity, Semaphore... 

Questions: should it execute tests? Should we use something like Sonar to check the code quality? Should it be able to deploy?

**Comment by lucianak** [comment]
Follow-up in #15

**Comment by Ewa032** [comment]
It was decided that we will use GitHub CI/CD actions
